language: python
python:
        - "3.5"
        - "3.6"
env:
        - TEST_DIR=backend
        - TEST_DIR=fleepbot
        - TEST_DIR=telegrambot 
        - TEST_DIR=common
install:
        - pip install -r $TEST_DIR/requirements.txt

script:
        cd $TEST_DIR && pytest tests.py

deploy:
        - provider: script
          script:
                  openssl aes-256-cbc -K $encrypted_5899b1a8b456_key -iv $encrypted_5899b1a8b456_iv -in .travis/travis_deploy_key.enc -out travis_deploy_key -d
                  scp deploy.sh $DEVUSER@$DEVREMOTE:~/
                  ssh $DEVUSE@$DEVREMOTE './deploy.sh dev'
          on:
                  branch: develop
