language: python
python:
        - "3.5"
env:
        - TEST_DIR=backend
        - TEST_DIR=fleepbot
        - TEST_DIR=telegrambot 
install:
        - pip install -r requirements.txt

script:
        cd $TEST_DIR && pytest
