language: python
python:
        - "3.6"

env:
    global:
        - NAME=Waldur-Chatbot
        - TRAVIS_DIR=.travis/
        - LOCAL_DEPLOY_SCRIPT=local_deploy.sh
        - PATH_TO_RUN_SCRIPT=backend
        - RUN_SCRIPT=run.py

install:
        - pip install -r requirements.txt

script:
        - pytest backend/test/*test.py
        - pytest common/test/*test.py

deploy:
     -  provider: script
        script: bash .travis/deploy.sh
        on:
                branch: master
                python: '3.6'

     -  provider: script
        script: bash .travis/deploy.sh
        on:
                branch: develop
                python: '3.6'
