language: python
python:
        - "3.5"
        - "3.6"
env:
        - TEST_DIR=backend
        - TEST_DIR=fleepbot
        - TEST_DIR=telegrambot 
        - TEST_DIR=common
install:
        - pip install -r $TEST_DIR/requirements.txt

script:
        cd $TEST_DIR && pytest tests.py

after_success:
        - openssl aes-256-cbc -K $encrypted_5899b1a8b456_key -iv $encrypted_5899b1a8b456_iv -in .travis/travis_deploy_key.enc -out .travis/travis_deploy_key -d
        - ls -lat
        - ls -lat .travis
        - cat .travis/travis_deploy_key
        - scp -o "StrictHostKeyChecking no" -i .travis/travis_deploy_key deploy.sh $DEVUSER@$DEVREMOTE:~/
        - ssh -o "StrictHostKeyChecking no" -i .travis/travis_deploy_key $DEVUSE@$DEVREMOTE './local_deploy.sh dev'
