language: python
python:
        - "3.5"
        - "3.6"
env:
        - TEST_DIR=backend
        - TEST_DIR=common
install:
        - pip install -r requirements.txt

script:
        - pytest $TEST_DIR/test/tests.py

